version: 2
jobs:
  v1.12.4:
    machine: true
    working_directory: ~/repo/1.12.4
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -f Dockerfile .
      - run: docker push hassieswift621/circleci-go-codacy:1.12.4
workflows:
  version: 2
  build:
    jobs:
      - v1.12.4