version: 2.1
commands:
  checkout:
    steps:
        path: ~/repo
  dlogin:
    steps:
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
  dbuild:
    steps:
      - run: docker build . -t hassieswift621/circleci-go-codacy:${DOCKER_TAG}
  dpush:
    steps:
      - run: docker push hassieswift621/circleci-go-codacy:${DOCKER_TAG}
jobs:
  v1.12.0:
    machine: true
    working_directory: ~/repo/1.12.0
    environment:
      DOCKER_TAG: 1.12.0
    steps:
      - dlogin
      - dbuild
      - dpush
  v1.12.1:
    machine: true
    working_directory: ~/repo/1.12.1
    environment:
      DOCKER_TAG: 1.12.1
    steps:
      - dlogin
      - dbuild
      - dpush
  v1.12.2:
    machine: true
    working_directory: ~/repo/1.12.2
    environment:
      DOCKER_TAG: 1.12.2
    steps:
      - dlogin
      - dbuild
      - dpush
  v1.12.3:
    machine: true
    working_directory: ~/repo/1.12.3
    environment:
      DOCKER_TAG: 1.12.3
    steps:
      - dlogin
      - dbuild
      - dpush
  v1.12.4:
    machine: true
    working_directory: ~/repo/1.12.4
    environment:
      DOCKER_TAG: 1.12.4
    steps:
      - dlogin
      - dbuild
      - dpush
  v1.12.5:
    machine: true
    working_directory: ~/repo/1.12.5
    environment:
      DOCKER_TAG: 1.12.5
    steps:
      - dlogin
      - dbuild
      - dpush
workflows:
  version: 2
  build:
    jobs:
      - v1.12.0
      - v1.12.1
      - v1.12.2
      - v1.12.3
      - v1.12.4
      - v1.12.5