version: 2.1
commands:
  dcheckout:
    steps:
      - checkout:
          path: ~/repo
  dlogin:
    steps:
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
  dbuild:
    steps:
      - run: docker build . -t hassieswift621/circleci-go-codacy:${DOCKER_TAG}
  dpush:
    steps:
      - run: docker push hassieswift621/circleci-go-codacy:${DOCKER_TAG}
jobs:
  v1120:
    machine: true
    working_directory: ~/repo/1.12.0
    environment:
      DOCKER_TAG: 1.12.0
    steps:
      - dcheckout
      - dlogin
      - dbuild
      - dpush
  v1121:
    machine: true
    working_directory: ~/repo/1.12.1
    environment:
      DOCKER_TAG: 1.12.1
    steps:
      - dcheckout
      - dlogin
      - dbuild
      - dpush
  v1122:
    machine: true
    working_directory: ~/repo/1.12.2
    environment:
      DOCKER_TAG: 1.12.2
    steps:
      - dcheckout
      - dlogin
      - dbuild
      - dpush
  v1123:
    machine: true
    working_directory: ~/repo/1.12.3
    environment:
      DOCKER_TAG: 1.12.3
    steps:
      - dcheckout
      - dlogin
      - dbuild
      - dpush
  v1124:
    machine: true
    working_directory: ~/repo/1.12.4
    environment:
      DOCKER_TAG: 1.12.4
    steps:
      - dcheckout
      - dlogin
      - dbuild
      - dpush
  v1125:
    machine: true
    working_directory: ~/repo/1.12.5
    environment:
      DOCKER_TAG: 1.12.5
    steps:
      - dcheckout
      - dlogin
      - dbuild
      - dpush
workflows:
  version: 2
  build:
    jobs:
      - v1120
      - v1121
      - v1122
      - v1123
      - v1124
      - v1125